import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:just_audio/just_audio.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../../core/state/app_state.dart';

class StudyPodScreen extends ConsumerStatefulWidget {
  const StudyPodScreen({super.key});

  @override
  ConsumerState<StudyPodScreen> createState() => _StudyPodScreenState();
}

class _StudyPodScreenState extends ConsumerState<StudyPodScreen>
    with SingleTickerProviderStateMixin {
  final AudioPlayer _player = AudioPlayer();
  late final AnimationController _pulse;

  bool _isFileLoaded = false;
  bool _isPlaying = false;
  Duration _duration = Duration.zero;
  Duration _position = Duration.zero;
  double _speed = 1.0;

  // Track which audio path is currently loaded so we avoid redundant reloads.
  String? _loadedPath;

  @override
  void initState() {
    super.initState();
    _pulse = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    );

    _player.durationStream.listen((d) {
      if (mounted) setState(() => _duration = d ?? Duration.zero);
    });

    _player.positionStream.listen((p) {
      if (mounted) setState(() => _position = p);
    });

    _player.playerStateStream.listen((s) {
      if (!mounted) return;
      setState(() {
        _isPlaying = s.playing;
        if (s.playing) {
          _pulse.repeat(reverse: true);
        } else {
          _pulse
            ..stop()
            ..animateTo(0,
                duration: const Duration(milliseconds: 400),
                curve: Curves.easeOut);
        }
      });
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // Load audio when the active document changes (e.g. after switching tabs).
    final path = ref.read(activeDocumentProvider)?.audioPath;
    _loadAudio(path);
  }

  Future<void> _loadAudio(String? path) async {
    if (path == _loadedPath) return; // nothing to do
    _loadedPath = path;

    await _player.stop();
    setState(() {
      _isFileLoaded = false;
      _isPlaying = false;
      _duration = Duration.zero;
      _position = Duration.zero;
    });

    if (path == null) return;

    try {
      final file = File(path);
      if (!await file.exists()) {
        debugPrint('StudyPodScreen: audio file not found at $path');
        return;
      }
      await _player.setFilePath(file.path);
      if (mounted) setState(() => _isFileLoaded = true);
    } catch (e) {
      debugPrint('StudyPodScreen._loadAudio error: $e');
    }
  }

  @override
  void dispose() {
    _pulse.dispose();
    _player.dispose();
    super.dispose();
  }

  // ---------------------------------------------------------------------------
  // Controls
  // ---------------------------------------------------------------------------

  void _togglePlay() {
    if (!_isFileLoaded) return;
    HapticFeedback.lightImpact();
    _isPlaying ? _player.pause() : _player.play();
  }

  void _seek(Duration delta) {
    if (!_isFileLoaded) return;
    HapticFeedback.lightImpact();
    var target = _position + delta;
    if (target < Duration.zero) target = Duration.zero;
    if (target > _duration) target = _duration;
    _player.seek(target);
  }

  void _cycleSpeed() {
    HapticFeedback.selectionClick();
    setState(() {
      if (_speed == 1.0) {
        _speed = 1.5;
      } else if (_speed == 1.5) {
        _speed = 2.0;
      } else {
        _speed = 1.0;
      }
      _player.setSpeed(_speed);
    });
  }

  Future<void> _share() async {
    try {
      final docDir = await getApplicationDocumentsDirectory();
      final file = File('${docDir.path}/study_pod_compiled.wav');
      if (await file.exists()) {
        await Share.shareXFiles([XFile(file.path)],
            text: 'Study podcast generated by Klassify!');
      }
    } catch (e) {
      debugPrint('StudyPodScreen._share error: $e');
    }
  }

  String _fmt(Duration d) {
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$m:$s';
  }

  // ---------------------------------------------------------------------------
  // Build
  // ---------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    // React to active document changes (e.g. user tapped a card in Workspace).
    ref.listen(activeDocumentProvider, (_, next) {
      _loadAudio(next?.audioPath);
    });

    final cs = Theme.of(context).colorScheme;
    final tt = Theme.of(context).textTheme;

    return Scaffold(
      backgroundColor: cs.surface,
      appBar: AppBar(
        title: const Text('Study Pod',
            style: TextStyle(fontWeight: FontWeight.w800, fontSize: 24)),
        elevation: 0,
        backgroundColor: Colors.transparent,
        actions: [
          IconButton(
            icon: const Icon(Icons.ios_share_rounded),
            tooltip: 'Share audio',
            onPressed: _isFileLoaded ? _share : null,
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              // Pulsing icon
              AnimatedBuilder(
                animation: _pulse,
                builder: (_, __) => Transform.scale(
                  scale: 1.0 + _pulse.value * 0.05,
                  child: Container(
                    height: 260,
                    width: 260,
                    decoration: BoxDecoration(
                      color: cs.primaryContainer,
                      shape: BoxShape.circle,
                      boxShadow: [
                        BoxShadow(
                          color: cs.primary
                              .withValues(alpha: 0.1 + _pulse.value * 0.2),
                          blurRadius: 40 + _pulse.value * 20,
                          spreadRadius: 10 + _pulse.value * 10,
                        ),
                      ],
                    ),
                    child: Icon(Icons.podcasts_rounded,
                        size: 110, color: cs.onPrimaryContainer),
                  ),
                ),
              ),
              const SizedBox(height: 48),
              Text(
                _isFileLoaded ? 'Now Playing' : 'No Audio Generated',
                style:
                    tt.headlineSmall?.copyWith(fontWeight: FontWeight.w900),
              ),
              const SizedBox(height: 8),
              Text(
                _isFileLoaded
                    ? 'AI-generated podcast'
                    : 'Scan a PDF in Workspace to generate audio',
                style: tt.bodyLarge
                    ?.copyWith(color: cs.onSurfaceVariant),
              ),
              const SizedBox(height: 40),

              // Progress
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(_fmt(_position),
                      style: const TextStyle(fontWeight: FontWeight.w600)),
                  Text(_fmt(_duration),
                      style: const TextStyle(fontWeight: FontWeight.w600)),
                ],
              ),
              const SizedBox(height: 4),
              SliderTheme(
                data: SliderTheme.of(context).copyWith(
                  trackHeight: 10,
                  thumbShape:
                      const RoundSliderThumbShape(enabledThumbRadius: 12),
                  overlayShape:
                      const RoundSliderOverlayShape(overlayRadius: 24),
                  activeTrackColor: cs.primary,
                  inactiveTrackColor: cs.surfaceContainerHighest,
                ),
                child: Slider(
                  value: _position.inMilliseconds
                      .toDouble()
                      .clamp(0.0, _duration.inMilliseconds.toDouble()),
                  max: _duration.inMilliseconds > 0
                      ? _duration.inMilliseconds.toDouble()
                      : 1.0,
                  onChanged: _isFileLoaded
                      ? (v) => _player
                          .seek(Duration(milliseconds: v.toInt()))
                      : null,
                ),
              ),
              const SizedBox(height: 24),

              // Transport controls
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  IconButton(
                    icon: const Icon(Icons.replay_10_rounded),
                    iconSize: 40,
                    onPressed: _isFileLoaded
                        ? () => _seek(const Duration(seconds: -10))
                        : null,
                  ),
                  const SizedBox(width: 20),
                  FloatingActionButton.large(
                    heroTag: 'play_pause',
                    onPressed: _isFileLoaded ? _togglePlay : null,
                    elevation: _isPlaying ? 1 : 6,
                    backgroundColor:
                        _isFileLoaded ? cs.primary : cs.surfaceContainerHighest,
                    foregroundColor: _isFileLoaded
                        ? cs.onPrimary
                        : cs.onSurfaceVariant,
                    child: Icon(
                      _isPlaying
                          ? Icons.pause_rounded
                          : Icons.play_arrow_rounded,
                      size: 52,
                    ),
                  ),
                  const SizedBox(width: 20),
                  IconButton(
                    icon: const Icon(Icons.forward_10_rounded),
                    iconSize: 40,
                    onPressed: _isFileLoaded
                        ? () => _seek(const Duration(seconds: 10))
                        : null,
                  ),
                ],
              ),
              const SizedBox(height: 20),

              // Speed toggle
              TextButton.icon(
                onPressed: _isFileLoaded ? _cycleSpeed : null,
                icon: const Icon(Icons.speed_rounded),
                label: Text('${_speed}x',
                    style: const TextStyle(
                        fontWeight: FontWeight.bold, fontSize: 16)),
                style: TextButton.styleFrom(
                    foregroundColor: cs.onSurfaceVariant),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
